/**
 * BOOTSTRAP STEPS, in order. Each step PLANS by reading the target's current
 * state and returns only the actions still needed, so running bootstrap again
 * does nothing (idempotent). Every outside call goes through `ctx.http`
 * (stubbed in tests/bootstrap-steps.test.ts), every secret through
 * `ctx.putSecret` (never printed). Action descriptions never contain a value.
 *
 *   1 database        migrations (recorded the way the Supabase CLI records
 *                     them), then the default-tenant shell
 *   2 cloudflare      DNS for <domain> and *.<domain>, the R2 photo bucket,
 *                     the Turnstile widget (its secret -> Worker secret)
 *   3 resend          the sending domain; its DNS records into Cloudflare;
 *                     a verification request
 *   4 worker-secrets  the Worker's secrets from the operator's environment
 *                     (CRON_SECRET generated)
 *     (deploy)        CI or the dashboard's git integration
 *   5 first-admin     the first super-admin, through the deployed site's own
 *                     Setup Wizard route (provider keys optional)
 *   6 stripe-webhooks the platform and Connect endpoints; their signing
 *                     secrets -> the settings row (after the first save)
 * The Worker config itself is generated by wrangler-config.ts (bootstrap
 * writes it to bootstrap-out/<domain>/wrangler.jsonc); deploying is CI or the
 * dashboard's git integration (BOOTSTRAP-RUNBOOK.md).
 */
import type { BootstrapInputs } from './inputs.ts';

export type HttpResponse = { status: number; json: any };
export type Http = (url: string, init?: { method?: string; headers?: Record<string, string>; body?: string }) => Promise<HttpResponse>;
export type Action = { describe: string; run: () => Promise<string> };
export type StepPlan = { done: string[]; todo: Action[]; blocked?: string };
export type Ctx = {
  inputs: BootstrapInputs;
  http: Http;
  /** Read an environment value by name (secrets included; never logged). */
  env: (name: string) => string;
  /** Store a secret where it belongs (Worker secret or settings column). */
  putSecret: (place: 'worker' | 'database', name: string, value: string) => Promise<void>;
  /** Migration files in order: [name, sql]. */
  migrations: Array<[string, string]>;
  /** Run SQL on the target database (Management API, or PGlite locally). */
  sql: (query: string) => Promise<any[]>;
  random: () => string;
  /** The names (never values) of the secrets the Worker already has. */
  workerSecretNames: () => Promise<Set<string>>;
};
export type Step = { id: string; title: string; needs: string[]; plan: (ctx: Ctx) => Promise<StepPlan> };

export const STRIPE_PLATFORM_EVENTS = [
  'checkout.session.completed', 'checkout.session.expired', 'payment_intent.succeeded',
  'customer.subscription.created', 'customer.subscription.updated', 'customer.subscription.deleted',
  'invoice.paid', 'invoice.payment_failed',
];
export const STRIPE_CONNECT_EVENTS = [
  'account.updated', 'checkout.session.completed', 'checkout.session.expired',
  'payment_intent.succeeded', 'charge.refunded', 'charge.dispute.created',
];

const DEFAULT_TENANT_ID = '00000000-0000-0000-0000-00000000000d';
const SETTINGS_ROW_ID = '00000000-0000-0000-0000-0000000000c0';
const missing = (ctx: Ctx, names: string[]) => names.filter((n) => !ctx.env(n));
const sqlText = (s: string) => "'" + s.replace(/'/g, "''") + "'";

// ── 1 database ──────────────────────────────────────────────────────────────
export const databaseStep: Step = {
  id: 'database', title: 'Schema, reference data and the default-tenant shell', needs: [],
  async plan(ctx) {
    // A database that already has our tables but no record of installing
    // them (the old stack, built by hand) must never get every migration
    // replayed over its data: fresh installs only.
    const existing = await ctx.sql("select (select count(*) from information_schema.tables where table_schema = 'public' and table_name = 'tenants')::int as tenants, (select count(*) from information_schema.tables where table_schema = 'supabase_migrations' and table_name = 'schema_migrations')::int as recorded");
    if (existing[0]?.tenants > 0 && existing[0]?.recorded === 0) {
      return { done: [], todo: [], blocked: 'this database already has a schema that bootstrap did not install (is this the OLD project?): refusing to replay migrations over it' };
    }
    await ctx.sql('create schema if not exists supabase_migrations; create table if not exists supabase_migrations.schema_migrations (version text primary key, name text, statements text[])');
    const applied = new Set((await ctx.sql('select version from supabase_migrations.schema_migrations')).map((r: any) => String(r.version)));
    const done: string[] = [];
    const todo: Action[] = [];
    for (const [name, sql] of ctx.migrations) {
      const version = name.split('_')[0];
      if (applied.has(version)) { done.push('migration ' + name); continue; }
      todo.push({ describe: 'apply migration ' + name, run: async () => {
        await ctx.sql(sql);
        await ctx.sql('insert into supabase_migrations.schema_migrations (version, name) values (' + sqlText(version) + ', ' + sqlText(name) + ') on conflict (version) do nothing');
        return 'applied';
      } });
    }
    const shell = await ctx.sql("select id from public.tenants where id = '" + DEFAULT_TENANT_ID + "'").catch(() => []);
    if (shell.length) done.push('default-tenant shell');
    else todo.push({ describe: 'create the default-tenant shell (same insert-if-missing as ensureDefaultTenant)', run: async () => {
      await ctx.sql("insert into public.tenants (id, slug, name, license_status) values ('" + DEFAULT_TENANT_ID + "', 'default', " + sqlText(ctx.inputs.name) + ", 'active') on conflict (id) do nothing");
      return 'created';
    } });
    if (todo.length) todo.push({ describe: 'reload the API schema cache', run: async () => { await ctx.sql("notify pgrst, 'reload schema'"); return 'reloaded'; } });
    return { done, todo };
  },
};

// ── 2 cloudflare ────────────────────────────────────────────────────────────
const CF = 'https://api.cloudflare.com/client/v4';
const cfHeaders = (ctx: Ctx) => ({ authorization: 'Bearer ' + ctx.env('CLOUDFLARE_BOOTSTRAP_TOKEN'), 'content-type': 'application/json' });

export const cloudflareStep: Step = {
  id: 'cloudflare', title: 'DNS, the photo bucket and the Turnstile widget', needs: ['CLOUDFLARE_BOOTSTRAP_TOKEN'],
  async plan(ctx) {
    const lack = missing(ctx, this.needs);
    if (lack.length) return { done: [], todo: [], blocked: 'needs ' + lack.join(', ') };
    if (!ctx.inputs.cloudflareAccountId) return { done: [], todo: [], blocked: 'needs the input cloudflareAccountId' };
    const h = cfHeaders(ctx);
    const { domain, cloudflareAccountId: acc, mediaBucket, name } = ctx.inputs;
    const zones = await ctx.http(CF + '/zones?name=' + encodeURIComponent(domain), { headers: h });
    const zone = zones.json?.result?.[0]?.id;
    if (!zone) return { done: [], todo: [], blocked: 'the zone ' + domain + ' is not on this Cloudflare account yet (add the domain first)' };
    const done: string[] = [];
    const todo: Action[] = [];
    // The Worker's routes need proxied records for the apex and every store.
    for (const host of [domain, '*.' + domain]) {
      const existing = await ctx.http(CF + '/zones/' + zone + '/dns_records?name=' + encodeURIComponent(host), { headers: h });
      if ((existing.json?.result || []).length) { done.push('DNS ' + host); continue; }
      todo.push({ describe: 'DNS: proxied AAAA ' + host + ' -> 100:: (served by the Worker routes)', run: async () => {
        const r = await ctx.http(CF + '/zones/' + zone + '/dns_records', { method: 'POST', headers: h, body: JSON.stringify({ type: 'AAAA', name: host, content: '100::', proxied: true, ttl: 1 }) });
        if (!r.json?.success) throw new Error('DNS ' + host + ': ' + JSON.stringify(r.json?.errors || r.status));
        return 'created';
      } });
    }
    const buckets = await ctx.http(CF + '/accounts/' + acc + '/r2/buckets', { headers: h });
    if ((buckets.json?.result?.buckets || []).some((b: any) => b.name === mediaBucket)) done.push('R2 bucket ' + mediaBucket);
    else todo.push({ describe: 'R2: create the private photo bucket ' + mediaBucket, run: async () => {
      const r = await ctx.http(CF + '/accounts/' + acc + '/r2/buckets', { method: 'POST', headers: h, body: JSON.stringify({ name: mediaBucket }) });
      if (!r.json?.success) throw new Error('R2: ' + JSON.stringify(r.json?.errors || r.status));
      return 'created';
    } });
    const widgets = await ctx.http(CF + '/accounts/' + acc + '/challenges/widgets', { headers: h });
    const widget = (widgets.json?.result || []).find((w: any) => (w.domains || []).includes(domain));
    if (widget) done.push('Turnstile widget for ' + domain + ' (site key ' + widget.sitekey + ', public)');
    else todo.push({ describe: 'Turnstile: create a managed widget for ' + domain + '; its secret becomes the Worker secret TURNSTILE_SECRET_KEY', run: async () => {
      const r = await ctx.http(CF + '/accounts/' + acc + '/challenges/widgets', { method: 'POST', headers: h, body: JSON.stringify({ name: name + ' signup', domains: [domain], mode: 'managed' }) });
      if (!r.json?.success) throw new Error('Turnstile: ' + JSON.stringify(r.json?.errors || r.status));
      await ctx.putSecret('worker', 'TURNSTILE_SECRET_KEY', String(r.json.result.secret));
      return 'created; site key ' + r.json.result.sitekey + ' (public: set it as the input turnstileSiteKey)';
    } });
    return { done, todo };
  },
};

// ── 3 resend ────────────────────────────────────────────────────────────────
const RS = 'https://api.resend.com';
export const resendStep: Step = {
  id: 'resend', title: 'The sending domain (records go into Cloudflare DNS)', needs: ['RESEND_BOOTSTRAP_KEY', 'CLOUDFLARE_BOOTSTRAP_TOKEN'],
  async plan(ctx) {
    const lack = missing(ctx, this.needs);
    if (lack.length) return { done: [], todo: [], blocked: 'needs ' + lack.join(', ') };
    const h = { authorization: 'Bearer ' + ctx.env('RESEND_BOOTSTRAP_KEY'), 'content-type': 'application/json' };
    const { domain } = ctx.inputs;
    const list = await ctx.http(RS + '/domains', { headers: h });
    let found = (list.json?.data || []).find((d: any) => d.name === domain);
    const done: string[] = [];
    const todo: Action[] = [];
    if (found?.status === 'verified') return { done: ['Resend domain ' + domain + ' (verified)'], todo };
    const zones = await ctx.http(CF + '/zones?name=' + encodeURIComponent(domain), { headers: cfHeaders(ctx) });
    const zone = zones.json?.result?.[0]?.id;
    if (!zone) return { done, todo, blocked: 'the zone ' + domain + ' is not on Cloudflare yet' };
    const addRecords = async (records: any[]) => {
      let n = 0;
      for (const rec of records || []) {
        const fqdn = rec.name === '@' || !rec.name ? domain : (String(rec.name).endsWith(domain) ? rec.name : rec.name + '.' + domain);
        const have = await ctx.http(CF + '/zones/' + zone + '/dns_records?type=' + rec.type + '&name=' + encodeURIComponent(fqdn), { headers: cfHeaders(ctx) });
        if ((have.json?.result || []).some((r: any) => String(r.content).replace(/"/g, '') === String(rec.value).replace(/"/g, ''))) continue;
        await ctx.http(CF + '/zones/' + zone + '/dns_records', { method: 'POST', headers: cfHeaders(ctx), body: JSON.stringify({ type: rec.type, name: fqdn, content: rec.value, ttl: 1, proxied: false, ...(rec.priority != null ? { priority: rec.priority } : {}) }) });
        n++;
      }
      return n;
    };
    if (!found) {
      todo.push({ describe: 'Resend: add the sending domain ' + domain + ', put its SPF/DKIM/MX records in Cloudflare DNS (DNS only), ask Resend to verify', run: async () => {
        const r = await ctx.http(RS + '/domains', { method: 'POST', headers: h, body: JSON.stringify({ name: domain }) });
        if (r.status >= 300) throw new Error('Resend: ' + JSON.stringify(r.json));
        const n = await addRecords(r.json?.records || []);
        await ctx.http(RS + '/domains/' + r.json.id + '/verify', { method: 'POST', headers: h });
        return 'added; ' + n + ' DNS record(s); verification requested (DNS can take minutes to hours)';
      } });
    } else {
      // Pending: if every record is already in DNS there is nothing to do but
      // wait for Resend to see it; only a missing record is work.
      const d = await ctx.http(RS + '/domains/' + found.id, { headers: h });
      const records = d.json?.records || [];
      let absent = 0;
      for (const rec of records) {
        const fqdn = rec.name === '@' || !rec.name ? domain : (String(rec.name).endsWith(domain) ? rec.name : rec.name + '.' + domain);
        const have = await ctx.http(CF + '/zones/' + zone + '/dns_records?type=' + rec.type + '&name=' + encodeURIComponent(fqdn), { headers: cfHeaders(ctx) });
        if (!(have.json?.result || []).some((r: any) => String(r.content).replace(/"/g, '') === String(rec.value).replace(/"/g, ''))) absent++;
      }
      if (!absent) return { done: ['Resend domain ' + domain + ': all ' + records.length + ' DNS records in place, waiting for Resend to verify (' + found.status + ')'], todo };
      done.push('Resend domain ' + domain + ' exists (' + found.status + ')');
      todo.push({ describe: 'Resend: add the ' + absent + ' missing DNS record(s) to Cloudflare, then ask Resend to verify again', run: async () => {
        const n = await addRecords(records);
        await ctx.http(RS + '/domains/' + found.id + '/verify', { method: 'POST', headers: h });
        return n + ' DNS record(s) added; verification requested';
      } });
    }
    return { done, todo };
  },
};

// ── 4 stripe-webhooks ───────────────────────────────────────────────────────
const ST = 'https://api.stripe.com/v1';
const form = (o: Record<string, string | string[] | boolean>) => Object.entries(o).flatMap(([k, v]) => Array.isArray(v) ? v.map((x) => encodeURIComponent(k + '[]') + '=' + encodeURIComponent(x)) : [encodeURIComponent(k) + '=' + encodeURIComponent(String(v))]).join('&');

export const stripeWebhooksStep: Step = {
  id: 'stripe-webhooks', title: 'Stripe webhooks (platform and Connect)', needs: ['STRIPE_BOOTSTRAP_KEY'],
  async plan(ctx) {
    const lack = missing(ctx, this.needs);
    if (lack.length) return { done: [], todo: [], blocked: 'needs ' + lack.join(', ') };
    const key = ctx.env('STRIPE_BOOTSTRAP_KEY');
    const h = { authorization: 'Bearer ' + key, 'content-type': 'application/x-www-form-urlencoded' };
    const mode = key.startsWith('sk_live_') || key.startsWith('rk_live_') ? 'LIVE' : 'test';
    const list = await ctx.http(ST + '/webhook_endpoints?limit=100', { headers: h });
    const endpoints = list.json?.data || [];
    const done: string[] = [];
    const todo: Action[] = [];
    const want: Array<{ url: string; events: string[]; connect: boolean; column: string }> = [
      { url: 'https://' + ctx.inputs.domain + '/api/stripe/webhook', events: STRIPE_PLATFORM_EVENTS, connect: false, column: 'payment_webhook_secret' },
      { url: 'https://' + ctx.inputs.domain + '/api/stripe/connect-webhook', events: STRIPE_CONNECT_EVENTS, connect: true, column: 'payment_connect_webhook_secret' },
    ];
    for (const w of want) {
      const have = endpoints.find((e: any) => e.url === w.url);
      if (have) {
        const lacking = w.events.filter((ev) => !(have.enabled_events || []).includes(ev) && !(have.enabled_events || []).includes('*'));
        if (!lacking.length) { done.push(mode + ' webhook ' + w.url); continue; }
        todo.push({ describe: mode + ' webhook ' + w.url + ': subscribe to ' + lacking.join(', '), run: async () => {
          await ctx.http(ST + '/webhook_endpoints/' + have.id, { method: 'POST', headers: h, body: form({ enabled_events: [...new Set([...(have.enabled_events || []), ...lacking])] }) });
          return 'updated';
        } });
        continue;
      }
      todo.push({ describe: 'create the ' + mode + (w.connect ? ' Connect' : ' platform') + ' webhook ' + w.url + ' (' + w.events.length + ' events); its signing secret -> settings.' + w.column, run: async () => {
        const r = await ctx.http(ST + '/webhook_endpoints', { method: 'POST', headers: h, body: form({ url: w.url, enabled_events: w.events, ...(w.connect ? { connect: true } : {}) }) });
        if (!r.json?.secret) throw new Error('Stripe: ' + JSON.stringify(r.json?.error?.message || r.status));
        await ctx.putSecret('database', w.column, String(r.json.secret));
        return 'created';
      } });
    }
    return { done, todo };
  },
};

// ── 5 worker-secrets ────────────────────────────────────────────────────────
export const WORKER_SECRETS_FROM_ENV = ['SUPABASE_URL', 'SUPABASE_ANON_KEY', 'SUPABASE_SERVICE_ROLE_KEY', 'MEDIA_S3_ACCESS_KEY_ID', 'MEDIA_S3_SECRET_ACCESS_KEY'];
export const workerSecretsStep: Step = {
  id: 'worker-secrets', title: 'The Worker\'s secrets', needs: WORKER_SECRETS_FROM_ENV,
  async plan(ctx) {
    const lack = missing(ctx, this.needs);
    if (lack.length) return { done: [], todo: [], blocked: 'set these in the operator\'s environment first: ' + lack.join(', ') };
    // Only what the Worker lacks: re-running never overwrites a secret, and
    // CRON_SECRET is generated once (a second run must not rotate it).
    const have = await ctx.workerSecretNames();
    const done: string[] = [];
    const todo: Action[] = [];
    const want: Array<[string, () => string, string]> = [
      ...WORKER_SECRETS_FROM_ENV.map((n) => [n, () => ctx.env(n), 'from the operator\'s environment'] as [string, () => string, string]),
      ['RESEND_FROM', () => ctx.inputs.sendingFrom, ctx.inputs.sendingFrom.replace(/<.*>/, '<…>')],
      ['CRON_SECRET', () => ctx.random(), 'generated'],
    ];
    for (const [n, value, how] of want) {
      if (have.has(n)) { done.push(n); continue; }
      todo.push({ describe: 'Worker secret ' + n + ' (' + how + ')', run: async () => { await ctx.putSecret('worker', n, value()); have.add(n); return 'set'; } });
    }
    return { done, todo };
  },
};

// ── 6 first-admin ───────────────────────────────────────────────────────────
export const firstAdminStep: Step = {
  id: 'first-admin', title: 'The first super-admin (through the site\'s own Setup Wizard route)', needs: ['BOOTSTRAP_ADMIN_PASSWORD'],
  async plan(ctx) {
    const lack = missing(ctx, this.needs);
    if (lack.length) return { done: [], todo: [], blocked: 'needs ' + lack.join(', ') + ' (the first admin\'s password; at least 12 characters)' };
    if (!ctx.inputs.adminEmail) return { done: [], todo: [], blocked: 'needs the input adminEmail' };
    if (ctx.env('BOOTSTRAP_ADMIN_PASSWORD').length < 12) return { done: [], todo: [], blocked: 'BOOTSTRAP_ADMIN_PASSWORD must be at least 12 characters' };
    const base = 'https://admin.' + ctx.inputs.domain;
    const status = await ctx.http(base + '/api/admin/setup').catch(() => ({ status: 0, json: null }));
    if (status.status === 0) return { done: [], todo: [], blocked: base + ' does not answer yet (deploy first)' };
    // Configured: the wizard says so, or the admin gate already demands a sign-in.
    if (status.json?.configured === true || status.json?.error === 'AUTH_REQUIRED') return { done: ['the platform is already configured (super-admin exists)'], todo: [] };
    // Provider keys, when the operator has them now (else the wizard, later).
    const providers: Record<string, string> = {};
    if (ctx.env('STRIPE_SECRET_KEY')) Object.assign(providers, { payment_provider: 'stripe', payment_api_key: ctx.env('STRIPE_SECRET_KEY') });
    if (ctx.env('RESEND_API_KEY')) Object.assign(providers, { mail_provider: 'resend', mail_api_key: ctx.env('RESEND_API_KEY') });
    const with_ = [providers.payment_provider && 'Stripe key', providers.mail_provider && 'Resend key'].filter(Boolean).join(' + ');
    return { done: [], todo: [{ describe: 'create the super-admin ' + ctx.inputs.adminEmail + ' via POST ' + base + '/api/admin/setup' + (with_ ? ' (with the ' + with_ + ' from the environment)' : ' (provider keys later, in the wizard)'), run: async () => {
      const r = await ctx.http(base + '/api/admin/setup', { method: 'POST', headers: { 'content-type': 'application/json', origin: base }, body: JSON.stringify({ adminEmail: ctx.inputs.adminEmail, adminPassword: ctx.env('BOOTSTRAP_ADMIN_PASSWORD'), ...providers }) });
      if (r.status >= 300) throw new Error('setup answered ' + r.status + ': ' + String(r.json?.error || '').slice(0, 200));
      return 'created';
    } }] };
  },
};

// Stripe last: the first save through the Setup Wizard writes the settings
// row's provider fields (an empty webhook secret included), so the signing
// secrets are stored after it.
export const STEPS: Step[] = [databaseStep, cloudflareStep, resendStep, workerSecretsStep, firstAdminStep, stripeWebhooksStep];
export { SETTINGS_ROW_ID };
