/**
 * WRANGLER CONFIG for a fresh install, generated from the bootstrap inputs
 * (pure; tested with a made-up name to prove nothing is hardcoded). Every
 * name, domain and address comes from the inputs; the rest (build output,
 * compatibility, observability, the storefront-routing defaults) is the same
 * for every install.
 */
import type { BootstrapInputs } from './inputs.ts';

export function wranglerConfig(i: BootstrapInputs): Record<string, unknown> {
  const vars: Record<string, string> = {
    STORAGE_PROVIDER: 'supabase',
    USE_POSTGRES_PRIMARY: 'true',
    PLATFORM_NAME: i.name,
    PLATFORM_ROOT_DOMAIN: i.domain,
    SUPPORT_EMAIL: i.supportEmail,
    OPERATOR_ALERT_EMAIL: i.alertEmail,
    TURNSTILE_EXPECTED_HOSTNAMES: i.domain,
    EMAIL_SINK_DOMAINS: 'proof.' + i.domain,
    MEDIA_BUCKET: i.mediaBucket,
    MEDIA_S3_ENDPOINT: i.cloudflareAccountId ? 'https://' + i.cloudflareAccountId + '.r2.cloudflarestorage.com' : '',
    MEDIA_S3_PUBLIC_BASE_URL: 'https://media.' + i.domain + '/media/r2',
    // Storefront routing: labels relative to the root, not names.
    STOREFRONT_LEGACY_HOSTS: 'shop,www,api',
    STOREFRONT_REDIRECT_HOSTS: 'shop',
    // The root domain is the platform's marketing site (on the old stack this
    // was a Worker secret; it is a switch, not a secret).
    PLATFORM_MARKETING_ROOT: 'true',
    // New features and signup stay off on a fresh install until switched on.
    ALLOW_MERCHANT_SIGNUP: 'false',
    STOREFRONT_SSR: 'off',
  };
  if (i.turnstileSiteKey) vars.TURNSTILE_SITE_KEY = i.turnstileSiteKey;
  if (i.legalEntity) vars.PLATFORM_LEGAL_ENTITY = i.legalEntity;
  if (i.oldRootDomains.length) vars.PLATFORM_OLD_ROOT_DOMAINS = i.oldRootDomains.join(',');
  const routes = [i.domain, ...i.oldRootDomains].flatMap((d) => [
    { pattern: d + '/*', zone_name: d },
    { pattern: '*.' + d + '/*', zone_name: d },
  ]);
  return {
    $schema: 'node_modules/wrangler/config-schema.json',
    name: i.worker,
    routes,
    r2_buckets: [{ binding: 'MEDIA_BUCKET_R2', bucket_name: i.mediaBucket }],
    main: '.open-next/worker.js',
    compatibility_date: '2025-01-01',
    compatibility_flags: ['nodejs_compat'],
    assets: { directory: '.open-next/assets', binding: 'ASSETS' },
    observability: { enabled: true },
    vars,
  };
}

/** The file text, with a header saying where it came from. */
export function wranglerConfigText(i: BootstrapInputs): string {
  return '// Generated by scripts/bootstrap (wrangler-config.ts) for ' + i.domain + '. Edit the bootstrap\n'
    + '// inputs and regenerate rather than editing names here. Secrets are NOT in this\n'
    + '// file: see scripts/bootstrap/secrets-manifest.ts.\n'
    + JSON.stringify(wranglerConfig(i), null, 2) + '\n';
}
