import { NextResponse } from 'next/server';
import { createRedisClient, ARCHIVE_LEDGER_KEY, loadProducts, safeParseRedisItem , getAdminPassword} from '@/lib/server-config';
import { sendAccountUpdateEmail, sendDeliveryIncentiveEmail } from '@/lib/email';

export const dynamic = 'force-dynamic';

const ALLOWED = ['PENDING_FULFILLMENT', 'LABEL_CREATED', 'SHIPPED', 'DELIVERED'];
const PROMOS_KEY = 'config:promos';

function issueKey(orderRef: string) {
  return `promo:delivery_credit_issued:${orderRef}`;
}

function generatePromoCode(prefix: string) {
  const root = (prefix || 'GOY').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6) || 'GOY';
  return `${root}-${Math.random().toString(36).slice(2, 7).toUpperCase()}-${Math.random().toString(36).slice(2, 5).toUpperCase()}`;
}

export async function POST(request: Request) {
  try {
    const redis = createRedisClient();
    if (!redis) return NextResponse.json({ error: 'Redis offline' }, { status: 500 });

    const body = await request.json();
    const password = String(body?.password || '');
    if (password !== getAdminPassword()) {
      return NextResponse.json({ error: 'Invalid password' }, { status: 403 });
    }

    const email = String(body?.email || '').toLowerCase();
    const variant = String(body?.variant || '');
    const size = String(body?.size || '');
    const shippingStatus = String(body?.shippingStatus || '');
    const trackingNumber = String(body?.trackingNumber || '').trim();
    
    if (!email || !variant || !ALLOWED.includes(shippingStatus)) {
      return NextResponse.json({ error: 'Bad payload' }, { status: 400 });
    }

    const all = await redis.lrange(ARCHIVE_LEDGER_KEY, 0, -1);
    const liveProducts = await loadProducts(redis);
    let updated = 0;
    let updatedEntry: any = null;
    
    for (let i = 0; i < all.length; i++) {
      const e = safeParseRedisItem<any>(all[i]);
      if (!e) continue;
      if (
        e.type === 'WINNER_CHARGED' &&
        String(e.email || '').toLowerCase() === email &&
        e.variant === variant &&
        (!size || e.size === size)
      ) {
        const updatedEntryData = { 
          ...e, 
          shippingStatus,
          ...(trackingNumber ? { trackingNumber } : {}),
        };
        await redis.lset(ARCHIVE_LEDGER_KEY, i, JSON.stringify(updatedEntryData));
        updated++;
        updatedEntry = updatedEntryData;
        
        // If status is DELIVERED, send final delivery email
        if (shippingStatus === 'DELIVERED') {
          try {
            await sendAccountUpdateEmail({
              to: email,
              product: variant,
              size: size || undefined,
              changeType: 'shipping',
              newAddress: `Delivered!${trackingNumber ? ` Tracking: ${trackingNumber}` : ''}`,
            });
          } catch (e) {
            console.error('[shipping] delivery email failed', e);
          }

          try {
            const product = Object.values(liveProducts).find((p: any) => p.name === variant || p.id === e.productId) as any;
            const triggerSizes = Array.isArray(product?.deliveryIncentiveTriggerSizes) ? product.deliveryIncentiveTriggerSizes.map(String) : [];
            const shouldIssue = product?.deliveryIncentiveEnabled === true && (triggerSizes.length === 0 || triggerSizes.includes(String(e.size || size)));
            const ref = String(e.orderRef || `${email}:${variant}:${size}`);
            const alreadyIssued = await redis.get(issueKey(ref));
            if (shouldIssue && !alreadyIssued) {
              const fixedDiscountCents = Math.max(0, Number(product.deliveryIncentiveCreditCents || 0));
              if (fixedDiscountCents > 0) {
                const promoCode = generatePromoCode(product.deliveryIncentiveCodePrefix || product.slug || 'GOY');
                const record = {
                  code: promoCode,
                  promoterName: 'Delivery Credit',
                  promoterEmail: '',
                  customerDiscountPercent: 0,
                  fixedDiscountCents,
                  minimumOrderSubtotalCents: Math.max(0, Number(product.deliveryIncentiveMinOrderSubtotalCents || 0)),
                  eligibleProductSlugs: Array.isArray(product.deliveryIncentiveEligibleProductSlugs) ? product.deliveryIncentiveEligibleProductSlugs : [],
                  eligibleSizes: Array.isArray(product.deliveryIncentiveEligibleSizes) ? product.deliveryIncentiveEligibleSizes : [],
                  issuedForEmail: email,
                  autoGenerated: true,
                  incentiveSourceProductId: product.id,
                  promoterPayoutPercent: 0,
                  maxUsesPerEmail: 1,
                  maxUsesTotal: 1,
                  timeLimited: false,
                  startAt: new Date().toISOString(),
                  endAt: null,
                  firstXWinnersDiscount: 0,
                  active: true,
                  uses: 0,
                  clicks: 0,
                  revenueAttributed: 0,
                  payoutOwedCents: 0,
                  payoutPaidCents: 0,
                  createdAt: new Date().toISOString(),
                };
                await redis.hset(PROMOS_KEY, { [promoCode]: JSON.stringify(record) });
                await redis.set(issueKey(ref), promoCode);
                await sendDeliveryIncentiveEmail({
                  to: email,
                  product: variant,
                  size: size || undefined,
                  code: promoCode,
                  creditAmountCents: fixedDiscountCents,
                  minimumOrderSubtotalCents: record.minimumOrderSubtotalCents,
                  eligibleProductSlugs: record.eligibleProductSlugs,
                  eligibleSizes: record.eligibleSizes,
                });
              }
            }
          } catch (e) {
            console.error('[shipping] incentive issue failed', e);
          }
        }
      }
    }

    // Also update the live pool entry if it exists
    try {
      const poolKey = `drop_pool:${variant}:${size}`;
      const items = await redis.lrange(poolKey, 0, -1);
      for (let i = 0; i < items.length; i++) {
        const parsed = safeParseRedisItem<any>(items[i]);
        if (parsed && String(parsed.email || '').toLowerCase() === email) {
          const updated = { ...parsed, shippingStatus, trackingNumber: trackingNumber || parsed.trackingNumber };
          await redis.lset(poolKey, i, JSON.stringify(updated));
          break;
        }
      }
    } catch {}

    return NextResponse.json({ success: true, updated });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}