import { NextResponse } from 'next/server';
import { createRedisClient, safeParseRedisItem, USERS_KEY, PROMO_CODES_KEY, promoUsedKey } from '@/lib/server-config';
import { getSessionUser } from '@/lib/session-auth';
import { sendWelcomeEmail } from '@/lib/email';

export const dynamic = 'force-dynamic';

const WELCOME_POINTS = 250;
const WELCOME_DISCOUNT_PERCENT = 10;

/** True when the code was already consumed by this email (used_emails set or
 * uses >= maxUsesTotal) — lets /account show "Used" instead of "Ready to use". */
async function isWelcomeCodeUsed(redis: any, code: string, email: string): Promise<boolean> {
  try {
    const inSet = await redis.sismember(promoUsedKey(code), email);
    if (inSet === 1) return true;
    const raw = await redis.hget(PROMO_CODES_KEY, code);
    const promo = safeParseRedisItem<any>(raw);
    const maxTotal = Number(promo?.maxUsesTotal || 0);
    return maxTotal > 0 && Number(promo?.uses || 0) >= maxTotal;
  } catch {
    return false;
  }
}

function generateWelcomeCode(email: string) {
  const seed = email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
  return `WELCOME-${seed}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`;
}

/**
 * Grants the account-creation welcome credit to users who signed up before the
 * credit existed. Idempotent: once a code exists on the account it is returned
 * as-is, never re-issued or changed.
 */
export async function POST(request: Request) {
  try {
    const sessionUser = await getSessionUser(request);
    if (!sessionUser) return NextResponse.json({ error: 'Login required.' }, { status: 401 });

    const redis = createRedisClient();
    if (!redis) return NextResponse.json({ error: 'Redis offline' }, { status: 500 });

    const rawUser = await redis.hget(USERS_KEY, sessionUser.userId);
    const user = safeParseRedisItem<any>(rawUser);
    if (!user || String(user.email || '').toLowerCase() !== sessionUser.email) {
      return NextResponse.json({ error: 'Account not found.' }, { status: 404 });
    }

    if (user.welcomePromoCode) {
      const used = await isWelcomeCodeUsed(redis, user.welcomePromoCode, user.email);
      return NextResponse.json({
        success: true,
        promoCode: user.welcomePromoCode,
        points: user.rewards || 0,
        used,
      });
    }

    const welcomeCode = generateWelcomeCode(user.email);
    const promo = {
      code: welcomeCode,
      promoterName: 'Welcome Credit',
      promoterEmail: '',
      customerDiscountPercent: WELCOME_DISCOUNT_PERCENT,
      fixedDiscountCents: 0,
      minimumOrderSubtotalCents: 0,
      eligibleProductSlugs: [],
      eligibleSizes: [],
      issuedForEmail: user.email,
      autoGenerated: true,
      welcome: true,
      promoterPayoutPercent: 0,
      maxUsesPerEmail: 1,
      maxUsesTotal: 1,
      timeLimited: false,
      startAt: new Date().toISOString(),
      endAt: null,
      firstXWinnersDiscount: 0,
      active: true,
      uses: 0,
      clicks: 0,
      revenueAttributed: 0,
      payoutOwedCents: 0,
      payoutPaidCents: 0,
      createdAt: new Date().toISOString(),
    };
    await redis.hset(PROMO_CODES_KEY, { [welcomeCode]: JSON.stringify(promo) });

    const points = Math.max(0, Number(user.rewards || 0) || 0);
    const updatedUser = {
      ...user,
      rewards: points > 0 ? points : WELCOME_POINTS,
      welcomePromoCode: welcomeCode,
      welcomePromoIssuedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    await redis.hset(USERS_KEY, { [user.id]: JSON.stringify(updatedUser) });

    try {
      await sendWelcomeEmail({
        to: user.email,
        points: updatedUser.rewards,
        promoCode: welcomeCode,
        discountPercent: WELCOME_DISCOUNT_PERCENT,
        siteUrl: process.env.NEXT_PUBLIC_SITE_URL || process.env.SITE_URL || '',
      });
    } catch (emailErr) {
      console.error('[claim-welcome] welcome email failed', emailErr);
    }

    return NextResponse.json({
      success: true,
      promoCode: welcomeCode,
      points: updatedUser.rewards,
      used: false,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
