import { NextResponse } from 'next/server';
import { createKvClient, safeParseKvItem, USERS_KEY, PROMO_CODES_KEY, promoUsedKey } from '@/lib/server-config';
import { readProfile, adjustRewards } from '@/lib/customer-profile';
import { mirrorRewardsToKv } from '@/lib/customer-profile-bridge';
import { ensureDefaultTenant } from '@/lib/tenant-context';
import { getSessionUser } from '@/lib/session-auth';
import { sendWelcomeEmail } from '@/lib/email';
import { getSiteUrl } from '@/lib/env';
import { randomBytes } from 'crypto';

export const dynamic = 'force-dynamic';

const WELCOME_POINTS = 250;
const WELCOME_DISCOUNT_PERCENT = 10;

/** True when the code was already consumed by this email (used_emails set or
 * uses >= maxUsesTotal) — lets /account show "Used" instead of "Ready to use". */
async function isWelcomeCodeUsed(redis: any, code: string, email: string): Promise<boolean> {
  try {
    const inSet = await redis.sismember(promoUsedKey(code), email);
    if (inSet === 1) return true;
    const raw = await redis.hget(PROMO_CODES_KEY, code);
    const promo = safeParseKvItem<any>(raw);
    const maxTotal = Number(promo?.maxUsesTotal || 0);
    return maxTotal > 0 && Number(promo?.uses || 0) >= maxTotal;
  } catch {
    return false;
  }
}

function generateWelcomeCode(email: string) {
  const seed = email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
  // crypto.randomBytes — the credit suffix must be unguessable (never Math.random).
  const suffix = randomBytes(3).toString('hex').toUpperCase().slice(0, 5);
  return `WELCOME-${seed}-${suffix}`;
}

/**
 * Grants the account-creation welcome credit to users who signed up before the
 * credit existed. Idempotent: once a code exists on the account it is returned
 * as-is, never re-issued or changed.
 */
export async function POST(request: Request) {
  try {
    const sessionUser = await getSessionUser(request);
    if (!sessionUser) return NextResponse.json({ error: 'Login required.' }, { status: 401 });

    const redis = createKvClient();
    if (!redis) return NextResponse.json({ error: 'Redis offline' }, { status: 500 });

    const rawUser = await redis.hget(USERS_KEY, sessionUser.userId);
    const user = safeParseKvItem<any>(rawUser);
    if (!user || String(user.email || '').toLowerCase() !== sessionUser.email) {
      return NextResponse.json({ error: 'Account not found.' }, { status: 404 });
    }

    // Anti-exploitation: welcome rewards only unlock after the email is verified.
    if (user.emailVerified === false) {
      return NextResponse.json({ error: 'Confirm your email first — the verification code unlocks your welcome rewards.' }, { status: 403 });
    }

    // H7: the balance comes from public.customers, not from the KV record.
    const tenantId = await ensureDefaultTenant();

    if (user.welcomePromoCode) {
      const used = await isWelcomeCodeUsed(redis, user.welcomePromoCode, user.email);
      const existing = await readProfile(tenantId, user.email);
      return NextResponse.json({
        success: true,
        promoCode: user.welcomePromoCode,
        points: existing?.rewardsBalance ?? 0,
        used,
      });
    }

    const welcomeCode = generateWelcomeCode(user.email);
    const promo = {
      code: welcomeCode,
      promoterName: 'Welcome Credit',
      promoterEmail: '',
      customerDiscountPercent: WELCOME_DISCOUNT_PERCENT,
      fixedDiscountCents: 0,
      minimumOrderSubtotalCents: 0,
      eligibleProductSlugs: [],
      eligibleSizes: [],
      issuedForEmail: user.email,
      autoGenerated: true,
      welcome: true,
      promoterPayoutPercent: 0,
      maxUsesPerEmail: 1,
      maxUsesTotal: 1,
      timeLimited: false,
      startAt: new Date().toISOString(),
      endAt: null,
      firstXWinnersDiscount: 0,
      active: true,
      uses: 0,
      clicks: 0,
      revenueAttributed: 0,
      payoutOwedCents: 0,
      payoutPaidCents: 0,
      createdAt: new Date().toISOString(),
    };
    await redis.hset(PROMO_CODES_KEY, { [welcomeCode]: JSON.stringify(promo) });

    // Grant the welcome points only if this account has never held any. The KV
    // version expressed that as `rewards: points > 0 ? points : WELCOME_POINTS`
    // — a read-modify-write on the same field two other paths also write, with
    // nothing stopping it from clobbering a concurrent change. Expressed as a
    // conditional DELTA it goes through the same compare-and-swap as every
    // other change to the balance.
    const before = await readProfile(tenantId, user.email);
    let points = before?.rewardsBalance ?? 0;
    if (points <= 0) {
      const granted = await adjustRewards(tenantId, user.email, WELCOME_POINTS);
      if (granted.ok) {
        points = granted.balance;
        await mirrorRewardsToKv(redis, user.email, granted.balance);
      } else {
        console.error(
          '[claim-welcome] welcome points NOT granted to ' + user.email + ' (' + granted.reason + ')',
        );
      }
    }

    const updatedUser = {
      ...user,
      rewards: points,
      welcomePromoCode: welcomeCode,
      welcomePromoIssuedAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    await redis.hset(USERS_KEY, { [user.id]: JSON.stringify(updatedUser) });

    try {
      await sendWelcomeEmail({
        to: user.email,
        points: updatedUser.rewards,
        promoCode: welcomeCode,
        discountPercent: WELCOME_DISCOUNT_PERCENT,
        siteUrl: getSiteUrl(),
      });
    } catch (emailErr) {
      console.error('[claim-welcome] welcome email failed', emailErr);
    }

    return NextResponse.json({
      success: true,
      promoCode: welcomeCode,
      points: updatedUser.rewards,
      used: false,
    });
  } catch (err: any) {
    console.error('[account/claim-welcome] failed', err?.message || err);
    return NextResponse.json({ error: 'Could not claim the welcome credit. Please try again.' }, { status: 500 });
  }
}
