import { NextResponse } from 'next/server';
import { createRedisClient, safeParseRedisItem, STORE_CONFIG_KEY, USERS_KEY, PROMO_CODES_KEY } from '@/lib/server-config';
import { getSessionUser } from '@/lib/session-auth';
import { randomBytes } from 'crypto';
import { rateLimitedResponse } from '@/lib/rate-limit';

export const dynamic = 'force-dynamic';

const DEFAULT_REWARDS = {
  pointsPerDollar: 100, // 100 points = $1.00 of credit
  minRedeemPoints: 100, // minimum redemption (250 welcome points = $2.50 credit)
  maxRedeemPoints: 0, // 0 = unlimited
};

async function loadRewardsConfig(redis: any) {
  try {
    const raw = await redis.get(STORE_CONFIG_KEY);
    const config = safeParseRedisItem<any>(raw) || {};
    return { ...DEFAULT_REWARDS, ...(config.rewards || {}) };
  } catch {
    return DEFAULT_REWARDS;
  }
}

export async function POST(request: Request) {
  try {
    const sessionUser = await getSessionUser(request);
    if (!sessionUser) {
      return NextResponse.json({ error: 'Login required.' }, { status: 401 });
    }

    const limited = await rateLimitedResponse('redeem_points', request, 10, 60);
    if (limited) return limited;

    const redis = createRedisClient();
    if (!redis) return NextResponse.json({ error: 'System offline.' }, { status: 500 });

    const body = await request.json();
    const requestedPoints = Math.floor(Number(body?.points || 0));
    const rewardsConfig = await loadRewardsConfig(redis);

    const pointsPerDollar = Math.max(1, Number(rewardsConfig.pointsPerDollar) || 100);
    const minRedeemPoints = Math.max(1, Number(rewardsConfig.minRedeemPoints) || 500);
    const maxRedeemPoints = Math.max(0, Number(rewardsConfig.maxRedeemPoints) || 0);

    if (!Number.isFinite(requestedPoints) || requestedPoints <= 0) {
      return NextResponse.json({ error: 'Enter how many points to redeem.' }, { status: 400 });
    }
    if (requestedPoints < minRedeemPoints) {
      return NextResponse.json({ error: `Minimum redemption is ${minRedeemPoints} points.` }, { status: 400 });
    }

    // Find the user record
    const raw = await redis.hgetall(USERS_KEY);
    let user: any = null;
    let userId = '';
    if (raw) {
      for (const [k, v] of Object.entries(raw)) {
        const u = safeParseRedisItem<any>(v);
        if (u && String(u.email || '').toLowerCase() === sessionUser.email) {
          user = u;
          userId = k;
          break;
        }
      }
    }
    if (!user) {
      return NextResponse.json({ error: 'Account not found.' }, { status: 404 });
    }

    const balance = Math.floor(Number(user.rewards || 0));
    if (balance < requestedPoints) {
      return NextResponse.json({ error: `You only have ${balance.toLocaleString()} points.` }, { status: 400 });
    }
    if (maxRedeemPoints > 0 && requestedPoints > maxRedeemPoints) {
      return NextResponse.json({ error: `Maximum redemption is ${maxRedeemPoints.toLocaleString()} points per transaction.` }, { status: 400 });
    }

    const dollars = Math.floor(requestedPoints / pointsPerDollar);
    if (dollars < 1) {
      return NextResponse.json({ error: `That amount is below $1.00 of credit (${pointsPerDollar} points = $1).` }, { status: 400 });
    }
    const usedPoints = dollars * pointsPerDollar;

    // Create a fixed-amount credit code. When gifting is enabled (admin
    // toggle) the code is NOT bound to this email so it can be shared/gifted;
    // otherwise it stays reserved to the redeemer.
    const giftingEnabled = rewardsConfig.giftingEnabled !== false;
    const seed = sessionUser.email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
    // crypto.randomBytes — the credit suffix must be unguessable (never Math.random).
    const code = `REWARD-${seed}-${randomBytes(3).toString('hex').toUpperCase().slice(0, 5)}`;
    const promo = {
      code,
      promoterName: 'Points Redemption',
      promoterEmail: '',
      customerDiscountPercent: 0,
      fixedDiscountCents: dollars * 100,
      minimumOrderSubtotalCents: 0,
      eligibleProductSlugs: [],
      eligibleSizes: [],
      issuedForEmail: giftingEnabled ? undefined : sessionUser.email,
      giftable: giftingEnabled === true,
      autoGenerated: true,
      welcome: false,
      promoterPayoutPercent: 0,
      maxUsesPerEmail: 1,
      maxUsesTotal: 1,
      timeLimited: false,
      startAt: new Date().toISOString(),
      endAt: null,
      firstXWinnersDiscount: 0,
      active: true,
      uses: 0,
      clicks: 0,
      revenueAttributed: 0,
      payoutOwedCents: 0,
      payoutPaidCents: 0,
      createdAt: new Date().toISOString(),
    };

    try {
      await redis.hset(PROMO_CODES_KEY, { [code]: JSON.stringify(promo) });
    } catch (err) {
      console.error('[redeem-points] save promo failed', err);
      return NextResponse.json({ error: 'Unable to create your credit right now.' }, { status: 500 });
    }

    // Deduct the points actually consumed.
    user.rewards = Math.max(0, balance - usedPoints);
    await redis.hset(USERS_KEY, { [userId]: JSON.stringify(user) });

    return NextResponse.json({
      success: true,
      message: `Redeemed ${usedPoints.toLocaleString()} points for a $${dollars.toFixed(2)} credit.`,
      code,
      dollars,
      usedPoints,
      remainingPoints: user.rewards,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || 'Unable to redeem points.' }, { status: 500 });
  }
}
