import { NextResponse } from 'next/server';
import { createRedisClient, safeParseRedisItem, USERS_KEY, PROMO_CODES_KEY, sessionKey } from '@/lib/server-config';
import { randomBytes } from 'crypto';
import { consumeCustomerVerifyCode } from '@/lib/customer-verify';
import { sendWelcomeEmail } from '@/lib/email';
import { getSiteUrl } from '@/lib/env';
import { isValidEmail } from '@/lib/validation';
import { rateLimitedResponse } from '@/lib/rate-limit';

export const dynamic = 'force-dynamic';

const SESSION_DURATION = 7 * 24 * 60 * 60;

/** Reward unlocked the moment the email is verified. */
const WELCOME_POINTS = 250;
const WELCOME_DISCOUNT_PERCENT = 10;

function generateWelcomeCode(email: string) {
  const seed = email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
  // crypto.randomBytes — the promo suffix must be unguessable (never Math.random).
  const suffix = randomBytes(3).toString('hex').toUpperCase().slice(0, 5);
  return `WELCOME-${seed}-${suffix}`;
}

function createSessionCookie(response: NextResponse, token: string) {
  response.cookies.set('goyunir_session', token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: SESSION_DURATION,
    path: '/',
  });
}

/** Confirm the emailed code, then unlock the account + welcome rewards + session. */
export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}));
    const email = String(body?.email || '').trim().toLowerCase();
    const code = String(body?.code || '').trim();
    if (!isValidEmail(email) || !/^\d{6}$/.test(code)) {
      return NextResponse.json({ error: 'Enter the 6-digit code from your email.' }, { status: 400 });
    }

    const limited = await rateLimitedResponse('auth_verify_email', request, 10, 60);
    if (limited) return limited;

    const redis = createRedisClient();
    if (!redis) return NextResponse.json({ error: 'System error' }, { status: 500 });

    const result = await consumeCustomerVerifyCode(redis, email, code);
    if (!result.ok) {
      return NextResponse.json({ error: result.error || 'Verification failed.' }, { status: 400 });
    }

    // Find the account (accounts older than this feature count as verified, so
    // an already-verified user reaching here just logs in).
    const raw = await redis.hgetall(USERS_KEY);
    let user: any = null;
    if (raw) {
      for (const [, v] of Object.entries(raw)) {
        const u = safeParseRedisItem<any>(v);
        if (u && String(u.email || '').toLowerCase() === email) { user = u; break; }
      }
    }
    if (!user) {
      return NextResponse.json({ error: 'Account not found — please sign up again.' }, { status: 404 });
    }
    if (user.emailVerified === true) {
      return NextResponse.json({ error: 'This email is already verified — log in instead.' }, { status: 400 });
    }

    // Unlock welcome rewards (issued only after the inbox is proven real).
    const welcomeCode = generateWelcomeCode(email);
    const welcomePromo = {
      code: welcomeCode,
      promoterName: 'Welcome Credit',
      promoterEmail: '',
      customerDiscountPercent: WELCOME_DISCOUNT_PERCENT,
      fixedDiscountCents: 0,
      minimumOrderSubtotalCents: 0,
      eligibleProductSlugs: [],
      eligibleSizes: [],
      issuedForEmail: email,
      autoGenerated: true,
      welcome: true,
      promoterPayoutPercent: 0,
      maxUsesPerEmail: 1,
      maxUsesTotal: 1,
      timeLimited: false,
      startAt: new Date().toISOString(),
      endAt: null,
      firstXWinnersDiscount: 0,
      active: true,
      uses: 0,
      clicks: 0,
      revenueAttributed: 0,
      payoutOwedCents: 0,
      payoutPaidCents: 0,
      createdAt: new Date().toISOString(),
    };
    try {
      await redis.hset(PROMO_CODES_KEY, { [welcomeCode]: JSON.stringify(welcomePromo) });
    } catch (promoErr) {
      console.error('[verify-email] welcome promo save failed', promoErr);
    }

    const updated = {
      ...user,
      emailVerified: true,
      rewards: WELCOME_POINTS,
      welcomePromoCode: welcomeCode,
      welcomePromoIssuedAt: new Date().toISOString(),
    };
    await redis.hset(USERS_KEY, { [user.id]: JSON.stringify(updated) });

    // Best-effort welcome email — the code is stored on the account regardless.
    try {
      await sendWelcomeEmail({
        to: email,
        points: WELCOME_POINTS,
        promoCode: welcomeCode,
        discountPercent: WELCOME_DISCOUNT_PERCENT,
        siteUrl: getSiteUrl(),
      });
    } catch (emailErr) {
      console.error('[verify-email] welcome email failed', emailErr);
    }

    const token = randomBytes(32).toString('hex');
    const expiresAt = Date.now() + SESSION_DURATION * 1000;
    await redis.setex(sessionKey(token), SESSION_DURATION, JSON.stringify({
      userId: user.id,
      email,
      role: user.role,
      rewards: WELCOME_POINTS,
      welcomePromoCode: welcomeCode,
      expiresAt,
    }));

    const response = NextResponse.json({
      success: true,
      verified: true,
      user: { id: user.id, email, role: user.role, rewards: WELCOME_POINTS, welcomePromoCode: welcomeCode },
    });
    createSessionCookie(response, token);
    return response;
  } catch (err: any) {
    console.error('[verify-email] Error:', err);
    return NextResponse.json({ error: 'Verification failed' }, { status: 500 });
  }
}
