import { NextResponse } from 'next/server';
import { createRedisClient, safeParseRedisItem } from '@/lib/server-config';
import { randomBytes, scryptSync } from 'crypto';
import { sendWelcomeEmail } from '@/lib/email';

function hashPassword(password: string, salt: string): string {
  return scryptSync(password, salt, 64).toString('hex');
}

const SESSION_DURATION = 7 * 24 * 60 * 60;

/** Reward unlocked the moment an account is created (matches the "Member perk"
 * card on the home page). Editable per-user later from /admin → Users. */
const WELCOME_POINTS = 250;
const WELCOME_DISCOUNT_PERCENT = 10;
const PROMOS_KEY = 'config:promos';

function generateWelcomeCode(email: string) {
  const seed = email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
  return `WELCOME-${seed}-${Math.random().toString(36).slice(2, 7).toUpperCase()}`;
}

function createSessionCookie(response: NextResponse, token: string) {
  response.cookies.set('goyunir_session', token, {
    httpOnly: true,
    secure: process.env.NODE_ENV === 'production',
    sameSite: 'lax',
    maxAge: SESSION_DURATION,
    path: '/',
  });
}

export async function POST(request: Request) {
  const { email, password } = await request.json();
  if (!email || !password) {
    return NextResponse.json({ error: 'Email and password required' }, { status: 400 });
  }
  const redis = createRedisClient();
  if (!redis) return NextResponse.json({ error: 'System error' }, { status: 500 });

  const normalizedEmail = String(email).trim().toLowerCase();

  // check if user exists
  const raw = await redis.hgetall('store:users');
  let existing = false;
  if (raw) {
    for (const [k, v] of Object.entries(raw)) {
      const u = safeParseRedisItem<any>(v);
      if (u && String(u.email || '').toLowerCase() === normalizedEmail) { existing = true; break; }
    }
  }
  if (existing) return NextResponse.json({ error: 'User already exists' }, { status: 400 });

  const salt = randomBytes(16).toString('hex');
  const hashed = hashPassword(password, salt);
  const id = `usr_${Date.now().toString(36)}`;

  // One-time member credit: 10% off first release, bound to this email.
  const welcomeCode = generateWelcomeCode(normalizedEmail);
  const welcomePromo = {
    code: welcomeCode,
    promoterName: 'Welcome Credit',
    promoterEmail: '',
    customerDiscountPercent: WELCOME_DISCOUNT_PERCENT,
    fixedDiscountCents: 0,
    minimumOrderSubtotalCents: 0,
    eligibleProductSlugs: [],
    eligibleSizes: [],
    issuedForEmail: normalizedEmail,
    autoGenerated: true,
    welcome: true,
    promoterPayoutPercent: 0,
    maxUsesPerEmail: 1,
    maxUsesTotal: 1,
    timeLimited: false,
    startAt: new Date().toISOString(),
    endAt: null,
    firstXWinnersDiscount: 0,
    active: true,
    uses: 0,
    clicks: 0,
    revenueAttributed: 0,
    payoutOwedCents: 0,
    payoutPaidCents: 0,
    createdAt: new Date().toISOString(),
  };
  try {
    await redis.hset(PROMOS_KEY, { [welcomeCode]: JSON.stringify(welcomePromo) });
  } catch (promoErr) {
    console.error('[signup] welcome promo save failed', promoErr);
  }

  const user = {
    id,
    email: normalizedEmail,
    password: `${salt}:${hashed}`,
    role: 'customer',
    rewards: WELCOME_POINTS,
    welcomePromoCode: welcomeCode,
    welcomePromoIssuedAt: new Date().toISOString(),
    createdAt: new Date().toISOString(),
  };
  await redis.hset('store:users', { [id]: JSON.stringify(user) });
  const token = randomBytes(32).toString('hex');
  const expiresAt = Date.now() + SESSION_DURATION * 1000;
  await redis.setex(`session:${token}`, SESSION_DURATION, JSON.stringify({
    userId: user.id,
    email: user.email,
    role: user.role,
    rewards: user.rewards || 0,
    welcomePromoCode: welcomeCode,
    expiresAt,
  }));

  // Best-effort welcome email with the points + promo code. Never fail signup
  // because an email provider hiccuped — the code is stored on the account and
  // shown in /account even when email delivery is unavailable.
  try {
    await sendWelcomeEmail({
      to: normalizedEmail,
      points: WELCOME_POINTS,
      promoCode: welcomeCode,
      discountPercent: WELCOME_DISCOUNT_PERCENT,
      siteUrl: process.env.NEXT_PUBLIC_SITE_URL || process.env.SITE_URL || '',
    });
  } catch (emailErr) {
    console.error('[signup] welcome email failed', emailErr);
  }

  const response = NextResponse.json({
    success: true,
    user: { id, email: normalizedEmail, role: 'customer', rewards: WELCOME_POINTS, welcomePromoCode: welcomeCode },
  });
  createSessionCookie(response, token);
  return response;
}
