import { NextResponse } from 'next/server';
import { createRedisClient, safeParseRedisItem, PROMO_CODES_KEY, promoUsedKey} from '@/lib/server-config';
import { adminAuthorized } from '@/lib/admin-verify';
import { appendAudit } from '@/app/api/admin/audit/route';

export const dynamic = 'force-dynamic';

export type PromoRecord = {
  code: string;
  promoterName: string;
  promoterEmail: string;
  customerDiscountPercent: number;
  fixedDiscountCents?: number;
  minimumOrderSubtotalCents?: number;
  eligibleProductSlugs?: string[];
  eligibleSizes?: string[];
  issuedForEmail?: string;
  autoGenerated?: boolean;
  incentiveSourceProductId?: string;
  promoterPayoutPercent: number;
  maxUsesPerEmail: number;
  maxUsesTotal: number;
  timeLimited: boolean;
  startAt: string | null;
  endAt: string | null;
  firstXWinnersDiscount: number;
  active: boolean;
  uses: number;
  clicks: number;
  revenueAttributed: number;
  payoutOwedCents: number;
  payoutPaidCents: number;
  createdAt: string;
};


async function loadPromos(redis: any): Promise<Record<string, PromoRecord>> {
  const raw = await redis.hgetall(PROMO_CODES_KEY);
  if (!raw) return {};
  const out: Record<string, PromoRecord> = {};
  for (const [k, v] of Object.entries(raw)) {
    const p = safeParseRedisItem<PromoRecord>(v);
    if (p) out[k] = p;
  }
  return out;
}

export async function GET(request: Request) {
  if (!(await adminAuthorized(request))) {
    return NextResponse.json({ promos: [] });
  }
  const redis = createRedisClient();
  if (!redis) return NextResponse.json({ promos: [] });
  const map = await loadPromos(redis);
  return NextResponse.json({ promos: Object.values(map) });
}

export async function POST(request: Request) {
  const redis = createRedisClient();
  if (!redis) return NextResponse.json({ error: 'Redis offline' }, { status: 500 });

  const body = await request.json();
  const password = String(body?.password || '');
  if (!(await adminAuthorized(request, password))) {
    return NextResponse.json({ error: 'Invalid password' }, { status: 403 });
  }

  const action = String(body?.action || 'upsert');
  const code = String(body?.code || '')
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9_-]/g, '');
  if (!code) return NextResponse.json({ error: 'Missing code' }, { status: 400 });

  if (action === 'delete') {
    await redis.hdel(PROMO_CODES_KEY, code);
    await redis.del(promoUsedKey(code));
    try {
      await appendAudit(redis, { action: 'PROMO_DELETED', detail: code, actor: 'admin' });
    } catch {}
    return NextResponse.json({ success: true });
  }

  const existingMap = await loadPromos(redis);
  const existing = existingMap[code];

  if (action === 'toggle') {
    if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    existing.active = !existing.active;
    await redis.hset(PROMO_CODES_KEY, { [code]: JSON.stringify(existing) });
    try {
      await appendAudit(redis, { action: 'PROMO_TOGGLED', detail: `${code} → ${existing.active ? 'active' : 'inactive'}`, actor: 'admin' });
    } catch {}
    return NextResponse.json({ success: true, promo: existing });
  }

  if (action === 'markPaid') {
    if (!existing) return NextResponse.json({ error: 'Not found' }, { status: 404 });
    existing.payoutPaidCents = existing.payoutOwedCents || 0;
    existing.payoutOwedCents = 0;
    await redis.hset(PROMO_CODES_KEY, { [code]: JSON.stringify(existing) });
    try {
      await appendAudit(redis, { action: 'PROMO_MARKED_PAID', detail: code, actor: 'admin' });
    } catch {}
    return NextResponse.json({ success: true, promo: existing });
  }

  // upsert = create or edit in place
  if (code.length < 3) {
    return NextResponse.json({ error: 'Code must be 3+ letters/numbers' }, { status: 400 });
  }

  const maxUsesPerEmail = Math.max(0, Number(body?.maxUsesPerEmail ?? existing?.maxUsesPerEmail ?? 1));
  const maxUsesTotal = Math.max(0, Number(body?.maxUsesTotal ?? existing?.maxUsesTotal ?? 0));

  const record: PromoRecord = {
    code,
    promoterName: String(body?.promoterName ?? existing?.promoterName ?? code),
    promoterEmail: String(body?.promoterEmail ?? existing?.promoterEmail ?? '').trim().toLowerCase(),
    customerDiscountPercent: Math.min(50, Math.max(0, Number(body?.customerDiscountPercent ?? existing?.customerDiscountPercent ?? 0))),
    fixedDiscountCents: Math.max(0, Number(body?.fixedDiscountCents ?? existing?.fixedDiscountCents ?? 0)) || 0,
    minimumOrderSubtotalCents: Math.max(0, Number(body?.minimumOrderSubtotalCents ?? existing?.minimumOrderSubtotalCents ?? 0)) || 0,
    eligibleProductSlugs: Array.isArray(body?.eligibleProductSlugs) ? body.eligibleProductSlugs.map(String) : (existing?.eligibleProductSlugs || []),
    eligibleSizes: Array.isArray(body?.eligibleSizes) ? body.eligibleSizes.map(String) : (existing?.eligibleSizes || []),
    issuedForEmail: String(body?.issuedForEmail ?? existing?.issuedForEmail ?? '').trim().toLowerCase() || undefined,
    autoGenerated: Boolean(body?.autoGenerated ?? existing?.autoGenerated ?? false),
    incentiveSourceProductId: String(body?.incentiveSourceProductId ?? existing?.incentiveSourceProductId ?? '').trim() || undefined,
    promoterPayoutPercent: Math.min(50, Math.max(0, Number(body?.promoterPayoutPercent ?? existing?.promoterPayoutPercent ?? 10))),
    maxUsesPerEmail,
    maxUsesTotal,
    timeLimited: body?.timeLimited ?? existing?.timeLimited ?? false,
    startAt: body?.startAt || existing?.startAt || null,
    endAt: body?.endAt || existing?.endAt || null,
    firstXWinnersDiscount: Math.min(50, Math.max(0, Number(body?.firstXWinnersDiscount ?? existing?.firstXWinnersDiscount ?? 0))),
    active: body?.active ?? existing?.active ?? true,
    uses: existing?.uses ?? 0,
    clicks: existing?.clicks ?? 0,
    revenueAttributed: existing?.revenueAttributed ?? 0,
    payoutOwedCents: existing?.payoutOwedCents ?? 0,
    payoutPaidCents: existing?.payoutPaidCents ?? 0,
    createdAt: existing?.createdAt || new Date().toISOString(),
  };

  await redis.hset(PROMO_CODES_KEY, { [code]: JSON.stringify(record) });
    try {
      await appendAudit(redis, { action: existing ? 'PROMO_UPDATED' : 'PROMO_CREATED', detail: code, actor: 'admin' });
    } catch {}
  return NextResponse.json({ success: true, promo: record });
}
