/**
 * CUSTOMER REWARDS & SESSION — shared by the signup and verify-email flows so
 * the two can never drift.
 *
 * Accounts earn the welcome points + one-time member credit exactly once, from
 * exactly one place. When an email provider is configured the reward is granted
 * only AFTER the inbox is verified (anti-bot). When no email provider is set up
 * there is nothing to verify against, so signup grants the reward immediately
 * and logs the customer straight in — the account is never held hostage behind
 * a code that cannot arrive.
 */

import { randomBytes } from 'crypto';
import { USERS_KEY, PROMO_CODES_KEY, sessionKey } from '@/lib/redis-keys';
import { sendWelcomeEmail } from '@/lib/email';
import { getSiteUrl } from '@/lib/env';
import { adjustRewards } from '@/lib/customer-profile';
import { ensureDefaultTenant } from '@/lib/tenant-context';

export const WELCOME_POINTS = 250;
export const WELCOME_DISCOUNT_PERCENT = 10;
export const CUSTOMER_SESSION_TTL_SECONDS = 7 * 24 * 60 * 60; // 7 days

export function generateWelcomeCode(email: string): string {
  const seed = email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
  // crypto.randomBytes — the promo suffix must be unguessable (never Math.random).
  const suffix = randomBytes(3).toString('hex').toUpperCase().slice(0, 5);
  return `WELCOME-${seed}-${suffix}`;
}

/**
 * Grant the welcome rewards (250 points + one-time member credit) and mark the
 * account verified. Saves the promo + the updated user atomically-ish (two hash
 * writes; the promo write is best-effort so a promo-save failure never blocks
 * the account). Does NOT send email or create a session — callers decide.
 *
 * H7: the POINTS now land in public.customers.rewards_balance, which is
 * authoritative (migration 00022). The KV record is still written, but with
 * whatever balance Postgres ended up holding — it is a display mirror for the
 * email templates this phase does not repoint, not a second source of truth.
 * See lib/customer-profile-bridge.ts.
 *
 * The grant is a DELTA (+250) where the KV version ASSIGNED `rewards = 250`.
 * That assignment silently erased points earned before verification: a
 * purchase made between signup and confirming the inbox awards points through
 * the Stripe webhook, and the welcome grant would have wiped them. A delta
 * cannot do that.
 *
 * `rewardsGranted: false` means the authoritative write did not happen. The
 * account is still verified and the promo still issued — those are separate
 * facts, and withholding them would lock a customer out of their account over
 * a points failure — but the points are not reported as granted when they
 * were not.
 */
export async function grantWelcomeRewards(
  redis: any,
  user: any,
  email: string,
): Promise<{ updatedUser: any; welcomeCode: string; rewardsGranted: boolean }> {
  const welcomeCode = generateWelcomeCode(email);

  const welcomePromo = {
    code: welcomeCode,
    promoterName: 'Welcome Credit',
    promoterEmail: '',
    customerDiscountPercent: WELCOME_DISCOUNT_PERCENT,
    fixedDiscountCents: 0,
    minimumOrderSubtotalCents: 0,
    eligibleProductSlugs: [],
    eligibleSizes: [],
    issuedForEmail: email,
    autoGenerated: true,
    welcome: true,
    promoterPayoutPercent: 0,
    maxUsesPerEmail: 1,
    maxUsesTotal: 1,
    timeLimited: false,
    startAt: new Date().toISOString(),
    endAt: null,
    firstXWinnersDiscount: 0,
    active: true,
    uses: 0,
    clicks: 0,
    revenueAttributed: 0,
    payoutOwedCents: 0,
    payoutPaidCents: 0,
    createdAt: new Date().toISOString(),
  };

  try {
    await redis.hset(PROMO_CODES_KEY, { [welcomeCode]: JSON.stringify(welcomePromo) });
  } catch (promoErr) {
    console.error('[customer-rewards] welcome promo save failed', promoErr);
  }

  // AUTHORITATIVE FIRST: Postgres decides the balance, KV is told the result.
  let balance = Math.max(0, Math.floor(Number(user.rewards || 0) || 0));
  let rewardsGranted = false;
  try {
    const tenantId = await ensureDefaultTenant();
    const result = await adjustRewards(tenantId, email, WELCOME_POINTS);
    if (result.ok) {
      balance = result.balance;
      rewardsGranted = true;
    } else {
      console.error(
        '[customer-rewards] WELCOME POINTS NOT GRANTED for ' + email + ' (' + result.reason + '). ' +
          'The account is verified and the promo issued, but the balance did not move.',
      );
    }
  } catch (err) {
    console.error('[customer-rewards] welcome points write threw', email, (err as Error)?.message || err);
  }

  const updatedUser = {
    ...user,
    emailVerified: true,
    rewards: balance,
    welcomePromoCode: welcomeCode,
    welcomePromoIssuedAt: new Date().toISOString(),
  };
  await redis.hset(USERS_KEY, { [user.id]: JSON.stringify(updatedUser) });

  return { updatedUser, welcomeCode, rewardsGranted };
}

/** Best-effort welcome email (skips silently when no email provider is set up). */
export async function trySendWelcomeEmail(email: string, promoCode: string): Promise<void> {
  try {
    await sendWelcomeEmail({
      to: email,
      points: WELCOME_POINTS,
      promoCode,
      discountPercent: WELCOME_DISCOUNT_PERCENT,
      siteUrl: getSiteUrl(),
    });
  } catch (emailErr) {
    console.error('[customer-rewards] welcome email failed', emailErr);
  }
}

/** Mint the 7-day customer session and return its token (cookie set by caller). */
export async function createCustomerSession(
  redis: any,
  email: string,
  userData: any,
): Promise<string> {
  const token = randomBytes(32).toString('hex');
  const expiresAt = Date.now() + CUSTOMER_SESSION_TTL_SECONDS * 1000;
  await redis.setex(
    sessionKey(token),
    CUSTOMER_SESSION_TTL_SECONDS,
    JSON.stringify({
      userId: userData.id,
      email,
      role: userData.role,
      rewards: userData.rewards ?? 0,
      welcomePromoCode: userData.welcomePromoCode,
      emailVerified: userData.emailVerified === true,
      expiresAt,
    }),
  );
  return token;
}
