/**
 * CUSTOMER REWARDS & SESSION — shared by the signup and verify-email flows so
 * the two can never drift.
 *
 * Accounts earn the welcome points + one-time member credit exactly once, from
 * exactly one place. When an email provider is configured the reward is granted
 * only AFTER the inbox is verified (anti-bot). When no email provider is set up
 * there is nothing to verify against, so signup grants the reward immediately
 * and logs the customer straight in — the account is never held hostage behind
 * a code that cannot arrive.
 */

import { randomBytes } from 'crypto';
import { USERS_KEY, PROMO_CODES_KEY, sessionKey } from '@/lib/redis-keys';
import { sendWelcomeEmail } from '@/lib/email';
import { getSiteUrl } from '@/lib/env';

export const WELCOME_POINTS = 250;
export const WELCOME_DISCOUNT_PERCENT = 10;
export const CUSTOMER_SESSION_TTL_SECONDS = 7 * 24 * 60 * 60; // 7 days

export function generateWelcomeCode(email: string): string {
  const seed = email.replace(/[^a-z0-9]/gi, '').slice(0, 4).toUpperCase() || 'MBR';
  // crypto.randomBytes — the promo suffix must be unguessable (never Math.random).
  const suffix = randomBytes(3).toString('hex').toUpperCase().slice(0, 5);
  return `WELCOME-${seed}-${suffix}`;
}

/**
 * Grant the welcome rewards (250 points + one-time member credit) and mark the
 * account verified. Saves the promo + the updated user atomically-ish (two hash
 * writes; the promo write is best-effort so a promo-save failure never blocks
 * the account). Does NOT send email or create a session — callers decide.
 */
export async function grantWelcomeRewards(
  redis: any,
  user: any,
  email: string,
): Promise<{ updatedUser: any; welcomeCode: string }> {
  const welcomeCode = generateWelcomeCode(email);

  const welcomePromo = {
    code: welcomeCode,
    promoterName: 'Welcome Credit',
    promoterEmail: '',
    customerDiscountPercent: WELCOME_DISCOUNT_PERCENT,
    fixedDiscountCents: 0,
    minimumOrderSubtotalCents: 0,
    eligibleProductSlugs: [],
    eligibleSizes: [],
    issuedForEmail: email,
    autoGenerated: true,
    welcome: true,
    promoterPayoutPercent: 0,
    maxUsesPerEmail: 1,
    maxUsesTotal: 1,
    timeLimited: false,
    startAt: new Date().toISOString(),
    endAt: null,
    firstXWinnersDiscount: 0,
    active: true,
    uses: 0,
    clicks: 0,
    revenueAttributed: 0,
    payoutOwedCents: 0,
    payoutPaidCents: 0,
    createdAt: new Date().toISOString(),
  };

  try {
    await redis.hset(PROMO_CODES_KEY, { [welcomeCode]: JSON.stringify(welcomePromo) });
  } catch (promoErr) {
    console.error('[customer-rewards] welcome promo save failed', promoErr);
  }

  const updatedUser = {
    ...user,
    emailVerified: true,
    rewards: WELCOME_POINTS,
    welcomePromoCode: welcomeCode,
    welcomePromoIssuedAt: new Date().toISOString(),
  };
  await redis.hset(USERS_KEY, { [user.id]: JSON.stringify(updatedUser) });

  return { updatedUser, welcomeCode };
}

/** Best-effort welcome email (skips silently when no email provider is set up). */
export async function trySendWelcomeEmail(email: string, promoCode: string): Promise<void> {
  try {
    await sendWelcomeEmail({
      to: email,
      points: WELCOME_POINTS,
      promoCode,
      discountPercent: WELCOME_DISCOUNT_PERCENT,
      siteUrl: getSiteUrl(),
    });
  } catch (emailErr) {
    console.error('[customer-rewards] welcome email failed', emailErr);
  }
}

/** Mint the 7-day customer session and return its token (cookie set by caller). */
export async function createCustomerSession(
  redis: any,
  email: string,
  userData: any,
): Promise<string> {
  const token = randomBytes(32).toString('hex');
  const expiresAt = Date.now() + CUSTOMER_SESSION_TTL_SECONDS * 1000;
  await redis.setex(
    sessionKey(token),
    CUSTOMER_SESSION_TTL_SECONDS,
    JSON.stringify({
      userId: userData.id,
      email,
      role: userData.role,
      rewards: userData.rewards ?? 0,
      welcomePromoCode: userData.welcomePromoCode,
      emailVerified: userData.emailVerified === true,
      expiresAt,
    }),
  );
  return token;
}
