import { NextResponse } from 'next/server';
import { createRedisClient, ARCHIVE_LEDGER_KEY, loadProducts, safeParseRedisItem, PROMO_CODES_KEY, promoCreditKey, poolKey} from '@/lib/server-config';
import { adminAuthorized } from '@/lib/admin-verify';
import { sendAccountUpdateEmail, sendDeliveryIncentiveEmail } from '@/lib/email';
import { resolveSamplerConfig } from '@/lib/sampler-config';
import { randomBytes } from 'crypto';

export const dynamic = 'force-dynamic';

const ALLOWED = ['PENDING_FULFILLMENT', 'LABEL_CREATED', 'SHIPPED', 'DELIVERED'];

function generatePromoCode(prefix: string) {
  // Neutral default prefix — never a template brand (customer-visible codes).
  const root = (prefix || 'DROP').toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 6) || 'DROP';
  const a = randomBytes(4).toString('hex').toUpperCase().slice(0, 5);
  const b = randomBytes(3).toString('hex').toUpperCase().slice(0, 3);
  return `${root}-${a}-${b}`;
}

export async function POST(request: Request) {
  try {
    const redis = createRedisClient();
    if (!redis) return NextResponse.json({ error: 'Redis offline' }, { status: 500 });

    const body = await request.json();
    const password = String(body?.password || '');
    if (!(await adminAuthorized(request, password))) {
      return NextResponse.json({ error: 'Invalid password' }, { status: 403 });
    }

    const email = String(body?.email || '').toLowerCase();
    const variant = String(body?.variant || '');
    const size = String(body?.size || '');
    const shippingStatus = String(body?.shippingStatus || '');
    const trackingNumber = String(body?.trackingNumber || '').trim();

    if (!email || !variant || !ALLOWED.includes(shippingStatus)) {
      return NextResponse.json({ error: 'Bad payload' }, { status: 400 });
    }

    const all = await redis.lrange(ARCHIVE_LEDGER_KEY, 0, -1);
    const liveProducts = await loadProducts(redis);
    let updated = 0;

    for (let i = 0; i < all.length; i++) {
      const entry = safeParseRedisItem<any>(all[i]);
      if (!entry) continue;
      if (
        entry.type === 'WINNER_CHARGED' &&
        String(entry.email || '').toLowerCase() === email &&
        entry.variant === variant &&
        (!size || entry.size === size)
      ) {
        const updatedEntry = {
          ...entry,
          shippingStatus,
          ...(trackingNumber ? { trackingNumber } : {}),
        };
        await redis.lset(ARCHIVE_LEDGER_KEY, i, JSON.stringify(updatedEntry));
        updated += 1;

        try {
          let message = `Status updated to: ${shippingStatus.replace(/_/g, ' ')}`;
          if (trackingNumber) message += `\nTracking Number: ${trackingNumber}`;
          if (shippingStatus === 'DELIVERED') {
            message = `Your order has been delivered!${trackingNumber ? `\nTracking Number: ${trackingNumber}` : ''}`;
          }
          await sendAccountUpdateEmail({
            to: email,
            product: variant,
            size: size || undefined,
            changeType: 'shipping',
            newAddress: message,
          });
        } catch (error) {
          console.error('[shipping-status] email failed', error);
        }

        if (shippingStatus === 'DELIVERED') {
          try {
            const product = Object.values(liveProducts).find((p: any) => p.name === variant || p.id === entry.productId) as any;
            // Per-sampler overrides win; product-level deliveryIncentive* defaults
            // are the fallback. Legacy `deliveryIncentiveTriggerSizes` still work.
            const sampler = resolveSamplerConfig(product, String(entry.size || size));
            const shouldIssue = product?.deliveryIncentiveEnabled === true && sampler !== null;
            const ref = String(entry.orderRef || `${email}:${variant}:${size}`);
            const alreadyIssued = await redis.get(promoCreditKey(ref));
            if (shouldIssue && !alreadyIssued) {
              const fixedDiscountCents = Math.max(0, sampler.creditCents);
              if (fixedDiscountCents > 0) {
                const promoCode = generatePromoCode(sampler.codePrefix || 'DROP');
                const neverExpires = sampler.neverExpires;
                const expiresDays = Math.max(1, sampler.expiresDays);
                const record = {
                  code: promoCode,
                  promoterName: 'Delivery Credit',
                  promoterEmail: '',
                  customerDiscountPercent: 0,
                  fixedDiscountCents,
                  minimumOrderSubtotalCents: sampler.minOrderSubtotalCents,
                  eligibleProductSlugs: sampler.eligibleProductSlugs,
                  eligibleSizes: sampler.eligibleSizes,
                  issuedForEmail: email,
                  autoGenerated: true,
                  incentiveSourceProductId: product.id,
                  promoterPayoutPercent: 0,
                  maxUsesPerEmail: 1,
                  maxUsesTotal: 1,
                  // Validity window: "Never expires" keeps it usable forever;
                  // otherwise the credit lapses after the configured days.
                  timeLimited: !neverExpires,
                  startAt: new Date().toISOString(),
                  endAt: neverExpires ? null : new Date(Date.now() + expiresDays * 86400000).toISOString(),
                  firstXWinnersDiscount: 0,
                  active: true,
                  uses: 0,
                  clicks: 0,
                  revenueAttributed: 0,
                  payoutOwedCents: 0,
                  payoutPaidCents: 0,
                  createdAt: new Date().toISOString(),
                };
                await redis.hset(PROMO_CODES_KEY, { [promoCode]: JSON.stringify(record) });
                await redis.set(promoCreditKey(ref), promoCode);
                await sendDeliveryIncentiveEmail({
                  to: email,
                  product: variant,
                  size: size || undefined,
                  code: promoCode,
                  creditAmountCents: fixedDiscountCents,
                  minimumOrderSubtotalCents: record.minimumOrderSubtotalCents,
                  eligibleProductSlugs: record.eligibleProductSlugs,
                  eligibleSizes: record.eligibleSizes,
                });
              }
            }
          } catch (error) {
            console.error('[shipping-status] incentive issue failed', error);
          }
        }
      }
    }

    try {
      const pool = poolKey(variant, size);
      const items = await redis.lrange(pool, 0, -1);
      for (let i = 0; i < items.length; i++) {
        const parsed = safeParseRedisItem<any>(items[i]);
        if (parsed && String(parsed.email || '').toLowerCase() === email) {
          const updated = { ...parsed, shippingStatus, trackingNumber: trackingNumber || parsed.trackingNumber };
          await redis.lset(pool, i, JSON.stringify(updated));
          break;
        }
      }
    } catch {}

    return NextResponse.json({ success: true, updated, message: `Updated ${updated} record(s) to ${shippingStatus}` });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}

export async function GET(request: Request) {
  try {
    const redis = createRedisClient();
    if (!redis) return NextResponse.json({ error: 'Redis offline' }, { status: 500 });

    const url = new URL(request.url);
    const password = url.searchParams.get('password') || '';
    if (!(await adminAuthorized(request, password))) {
      return NextResponse.json({ error: 'Invalid password' }, { status: 403 });
    }

    const email = url.searchParams.get('email')?.toLowerCase() || '';
    const variant = url.searchParams.get('variant') || '';
    const size = url.searchParams.get('size') || '';

    if (!email || !variant) {
      return NextResponse.json({ error: 'Missing email or variant' }, { status: 400 });
    }

    const all = await redis.lrange(ARCHIVE_LEDGER_KEY, 0, -1);
    const entries = all
      .map((item) => safeParseRedisItem<any>(item))
      .filter((entry) =>
        entry &&
        entry.type === 'WINNER_CHARGED' &&
        String(entry.email || '').toLowerCase() === email &&
        entry.variant === variant &&
        (!size || entry.size === size),
      )
      .sort((a, b) => new Date(b.registeredAt).getTime() - new Date(a.registeredAt).getTime());

    const latest = entries[0] || null;

    return NextResponse.json({
      shippingStatus: latest?.shippingStatus || 'PENDING_FULFILLMENT',
      trackingNumber: latest?.trackingNumber || null,
      entries: entries.slice(0, 10),
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}